# .travis.yml
sudo: required
language: node_js
services:
  - docker
node_js:
  - '8'

branches:
  only:
    - master

cache:
  yarn: true

before_install:
- docker pull shayanealcantara/gh-pages-docker-travis

script:
  - docker run shayanealcantara/gh-pages-docker-travis bash -c "sh publish.sh"